### ISSUE TITLE
remove and add to Watchlist not persisting

### ISSUE THREAD

**Issue by styliii** [FinNerds/AndroidApp#28]
@mikeng13 can you check out this function and test if it's actually persisting when i call ```removeFromWatchlist``` and ```addToWatchlist```?

https://github.com/FinNerds/AndroidApp/blob/master/WealthNOW/app/src/main/java/com/finnerds/wealthnow/activities/DetailActivity.java#L92

**Comment by mikeng13** [comment]
@styliii 

Hey this actually works fine. I am seeing the changes persisted in the watchlist. The problem is that we are calling Stock.getBySymbol, which works if you've searched the stock before. So when you hook this up to the home activity you should pass the stock from the home fragment to this via the bundle.

**Comment by styliii** [comment]
hey @mikeng13, can you explain this to me?  in the DefaultWatchList, stockList is null, but watchedStocks has "BAC" in there.  Isn't stockList supposed to reflect what's in watchedStocks?

![screenshot 2015-03-30 20 47 14](https://cloud.githubusercontent.com/assets/1683182/6912047/c53cfcd4-d71e-11e4-85ba-daae2e477b98.png)
